name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install hts_engine_API
      run: |
        git clone https://github.com/r9y9/hts_engine_API
        cd hts_engine_API/src && mkdir -p build && cd build && cmake .. && sudo make -j install
    - name: configure
      run: cd src && mkdir build && cd build && cmake ..
    - name: build
      run:  cd src/build && make -j
